add new post

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,49 +1,72 @@
-#!/bin/sh
+#!/usr/bin/perl
 #
-# An example hook script to verify what is about to be committed.
-# Called by "git commit" with no arguments.  The hook should
-# exit with non-zero status after issuing an appropriate message if
-# it wants to stop the commit.
+# Pre-commit hook for running checkstyle on changed Java sources
 #
-# To enable this hook, rename this file to "pre-commit".
+# To use this you need:
+# 1. checkstyle's jar file somewhere
+# 2. a checkstyle XML check file somewhere
+# 3. To configure git:
+#   * git config --add checkstyle.jar <location of jar>
+#   * git config --add checkstyle.checkfile <location of checkfile>
+#   * git config --add java.command <path to java executale> [optional
+#     defaults to assuming it's in your path]
+# 4. Put this in your .git/hooks directory as pre-commit
+#
+# Now, when you commit, you will be disallowed from doing so
+# until you pass your checkstyle checks.
 
-if git rev-parse --verify HEAD >/dev/null 2>&1
-then
-	against=HEAD
-else
-	# Initial commit: diff against an empty tree object
-	against=$(git hash-object -t tree /dev/null)
-fi
+$command = "git-diff-index --cached HEAD 2>&1 | sed 's/^:.*     //' | uniq";
+open (FILES,$command . "|") || die "Cannot run '$command': $!\n";
 
-# If you want to allow non-ASCII filenames set this variable to true.
-allownonascii=$(git config --type=bool hooks.allownonascii)
+$CONFIG_CHECK_FILE = "checkstyle.checkfile";
+$CONFIG_JAR = "checkstyle.jar";
+$CONFIG_JAVA = "java.command";
 
-# Redirect output to stderr.
-exec 1>&2
+$check_file = `git config --get $CONFIG_CHECK_FILE`;
+$checkstyle_jar = `git config --get $CONFIG_JAR`;
+$java_command = `git config --get $CONFIG_JAVA`;
 
-# Cross platform projects tend to avoid non-ASCII filenames; prevent
-# them from being added to the repository. We exploit the fact that the
-# printable range starts at the space character and ends with tilde.
-if [ "$allownonascii" != "true" ] &&
-	# Note that the use of brackets around a tr range is ok here, (it's
-	# even required, for portability to Solaris 10's /usr/bin/tr), since
-	# the square bracket bytes happen to fall in the designated range.
-	test $(git diff --cached --name-only --diff-filter=A -z $against |
-	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
-then
-	cat <<\EOF
-Error: Attempt to add a non-ASCII file name.
+if (!$check_file || !$checkstyle_jar)
+{
+   die "You must configure checkstyle in your git config:\n"
+   . "\t$CONFIG_CHECK_FILE - path to your checkstyle.xml file\n"
+   . "\t$CONFIG_JAR - path to your checkstyle jar file\n"
+   . "\t$CONFIG_JAVA - path to your java executable (optional)\n"
+   ;
+}
 
-This can cause problems if you want to work with people on other platforms.
+$java_command = "java" if (!$java_command);
 
-To be portable it is advisable to rename the file.
+chomp $check_file;
+chomp $checkstyle_jar;
+chomp $java_command;
 
-If you know what you are doing you can disable this check using:
+$command = "$java_command -jar $checkstyle_jar -c $check_file";
 
-  git config hooks.allownonascii true
-EOF
-	exit 1
-fi
+@java_files = ();
 
-# If there are whitespace errors, print the offending file names and fail.
-exec git diff-index --check --cached $against --
+foreach (<FILES>)
+{
+   chomp;
+   next if (!(/\.java$/));
+   push @java_files,$_;
+   $command .= " ";
+   $command .= $_;
+}
+if ($#java_files >= 0)
+{
+   if (&run_and_log_system ($command))
+   {
+       print STDERR "Commit aborted.\n";
+       exit -1;
+   }
+}
+
+exit 0;
+
+sub run_and_log_system
+{
+   ($cmd) = @_;
+
+   system $cmd;
+}
